name = "OptiGraphsBase"
uuid = "b60d93bb-0b16-4596-9aba-1c050d4bcbe6"
authors = ["jalving <jhjalving@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
